description: Fetch and checkout single branch


inputs:
  token:
    description: Login token
    required: false
    default: ${{ github.token }}

  repository:
    description: Repo checkout
    required: false
    default: ${{ github.repository }}

  branch:
    description: Branch checkout
    required: false
    default: ${{ github.ref_name }}

  path:
    description: Path checkout
    required: false
    default: "."

  depth:
    description: Commit history
    required: false
    default: 1

  auto:
    description: Automatic handling
    required: false
    default: ''


runs:
  using: composite

  steps:
    - if: inputs.auto != ''
      uses: li1ht2ay-3es/gi1-ac2io3s@user-action



    - shell: bash
      run: |
        rm -rf ..?* .[!.]* *



    - shell: bash
      run: |
        branch=${{ inputs.branch }}
        if [[ "$branch" == "" ]]; then
          branch="${{ github.ref_name }}"
        fi


        ##########


        git clone --depth ${{ inputs.depth }} --branch $branch --single-branch https://${{ inputs.token }}@github.com/${{ inputs.repository }}.git ${{ inputs.path }}
        git reset --hard origin/$branch

        git for-each-ref --shell 'refs/remotes/origin'
